# Generated by Django 5.0.6 on 2024-05-22 00:00

from django.db import migrations

services_data = [
    {
        "nombre": "Control de Salud Infantil",
        "tipo": "Atención Médica",
        "descripcion": "Control periódico para niños y niñas."
    },
    {
        "nombre": "Control de Morbilidad",
        "tipo": "Atención Médica",
        "descripcion": "Atención de enfermedades agudas."
    },
    {
        "nombre": "Control de Salud Cardiovascular",
        "tipo": "Atención Médica",
        "descripcion": "Seguimiento a pacientes con enfermedades cardiovasculares."
    },
    {
        "nombre": "Atención Dental",
        "tipo": "Atención Dental",
        "descripcion": "Servicios odontológicos generales."
    },
    {
        "nombre": "Curaciones",
        "tipo": "Procedimientos",
        "descripcion": "Limpieza y tratamiento de heridas."
    },
    {
        "nombre": "Vacunación",
        "tipo": "Procedimientos",
        "descripcion": "Administración de vacunas del programa nacional."
    },
    {
        "nombre": "Toma de Muestras",
        "tipo": "Procedimientos",
        "descripcion": "Toma de muestras para exámenes de laboratorio."
    },
    {
        "nombre": "Farmacia",
        "tipo": "Soporte",
        "descripcion": "Dispensación de medicamentos."
    },
]

def populate_services(apps, schema_editor):
    Servicio = apps.get_model('cesfamApp', 'Servicio')
    for service_info in services_data:
        Servicio.objects.create(**service_info)

def delete_services(apps, schema_editor):
    Servicio = apps.get_model('cesfamApp', 'Servicio')
    service_names = [service['nombre'] for service in services_data]
    Servicio.objects.filter(nombre__in=service_names).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cesfamApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_services, reverse_code=delete_services),
    ]
