# Generated by Django 5.0.6 on 2024-05-23 00:00

from django.db import migrations

# Mapeo de nombres de días a números y viceversa
dias_a_numero = {
    'lunes': '0', 'martes': '1', 'miércoles': '2', 'jueves': '3',
    'viernes': '4', 'sábado': '5', 'domingo': '6'
}
numero_a_dias = {v: k.capitalize() for k, v in dias_a_numero.items()}

def convertir_dias_a_numeros(apps, schema_editor):
    """
    Convierte los nombres de los días de la semana (ej. 'Lunes') a su representación
    numérica como texto (ej. '0') en el campo `dia` del modelo Horario.
    """
    Horario = apps.get_model('cesfamApp', 'Horario')
    for horario in Horario.objects.all():
        dia_lower = horario.dia.lower().strip()
        if dia_lower in dias_a_numero:
            horario.dia = dias_a_numero[dia_lower]
            horario.save(update_fields=['dia'])

def revertir_numeros_a_dias(apps, schema_editor):
    """
    Revierte los números en formato de texto (ej. '0') a sus nombres de día
    correspondientes (ej. 'Lunes').
    """
    Horario = apps.get_model('cesfamApp', 'Horario')
    for horario in Horario.objects.all():
        if horario.dia in numero_a_dias:
            horario.dia = numero_a_dias[horario.dia]
            horario.save(update_fields=['dia'])

class Migration(migrations.Migration):

    dependencies = [
        ('cesfamApp', '0002_initial_services'),
    ]

    operations = [
        migrations.RunPython(convertir_dias_a_numeros, reverse_code=revertir_numeros_a_dias),
    ]
