# Generated by Django 5.0.6 on 2024-05-23 00:01

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('cesfamApp', '0003_convert_day_names_to_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='dia',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Día de la semana en que el profesional atiende'),
        ),
    ]
