# Generated by Django 5.2.7 on 2025-12-02 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfamApp', '0004_alter_horario_dia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensaje',
            options={'ordering': ['-fecha'], 'verbose_name': 'Mensaje del Sistema', 'verbose_name_plural': 'Mensajes del Sistema'},
        ),
        migrations.AddField(
            model_name='mensaje',
            name='message_type',
            field=models.CharField(choices=[('notification', 'Notificación General'), ('alert', 'Alerta del Sistema'), ('appointment_reminder', 'Recordatorio de Cita'), ('system_update', 'Actualización del Sistema'), ('other', 'Otro')], default='notification', max_length=50, verbose_name='Tipo de Mensaje del Sistema'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_mensajes_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_mensajes_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Remitente'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asunto de la Conversación')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversacion_cita', to='cesfamApp.cita', verbose_name='Cita Relacionada')),
                ('is_read_by', models.ManyToManyField(blank=True, related_name='read_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Leído por')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Participantes')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenido del Mensaje')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de Envío')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='cesfamApp.conversation', verbose_name='Conversación')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to=settings.AUTH_USER_MODEL, verbose_name='Leído por')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['timestamp'],
            },
        ),
    ]
