# Generated by Django 5.2.8 on 2025-12-04 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesfamApp', '0005_alter_mensaje_options_mensaje_message_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='especialidad',
        ),
    ]
