# Generated by Django 5.2.8 on 2025-11-29 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfamApp', '0007_anuncio_mensaje_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('bloqueado', models.BooleanField(default=False)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cesfamApp.profesional')),
            ],
            options={
                'db_table': 'horario',
            },
        ),
    ]
